services:
  backend:
    build: ./backend
    container_name: viewers_leaderboard_backend
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      MONGO_CONN_STR: mongodb://db_username:db_pwd@mongo:27017/
    env_file:
      - .env.backend
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: viewers_leaderboard_frontend
    ports:
      - "5173:80"
    env_file:
      - .env.frontend
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    restart: always
    container_name: viewers_leaderboard_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_username
      MONGO_INITDB_ROOT_PASSWORD: db_pwd
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: